
import "./globals.css";
import ReduxProvidor from "@/redux/redux.providor";
import { Toaster } from "sonner";


export const metadata = {
  title: "blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

<ReduxProvidor>
  {children}
  <Toaster richColors/>
</ReduxProvidor>
       
      </body>
    </html>
  );
}
